services:
    Wasinger\BundleAssetProviderBundle\Command\AssetsSourcesCommand:
        arguments:
            - '@filesystem'
        tags:
            - 'console.command'
    Wasinger\BundleAssetProviderBundle\Command\CheckAssetDependenciesCommand:
        arguments:
            - '@filesystem'
        tags:
            - 'console.command'


